Mobile first
carlosmuerto/capstone-project-conference-page pull request #4
Opened 2022-07-25 22:31 UTC by carlosmuerto

**Milestone 1 - content (1h)**

 - [ ] Choose the topic for your website.
 - [x] Choose images, text, icons, and fonts.

**Milestone 2 - mobile first (5h)**

 - [ ] Create the 2 pages for mobile.
   - [x] header
   - [ ] footer
   - [ ] Home Page
     - [ ] headline
     - [ ] main program
     - [ ] features 
   - [ ] about Page 
     - [ ] headline
     - [ ] about info
 - [x] Deploy the project.

2022-07-27 22:47 UTC, keroloussamy requested changes
Hi @carlosmuerto, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly add the link for a video presenting the features of the project, in your README file.
- [ ] Kindly update your link for your deployed project, in your README file.

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Optional suggestions
_Check the comments under the review._

- [ ] x

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 22:47 UTC, keroloussamy commented on index.html
> +      </div>
- [ ] Kindly make sure the all cards are aligned with each other.

![image](https://user-images.githubusercontent.com/35535130/181384893-3c2b5fe5-cdf5-42c4-aeb5-d244aaf0f0e1.png)

2022-07-27 22:47 UTC, keroloussamy commented on index.html
> +    </section>
- [ ] Kindly change the style for this button, to match the original design.

Your design
![image](https://user-images.githubusercontent.com/35535130/181385120-d50174e5-274f-40dd-8bf3-86b3d2f8038b.png)

Original design 
![image](https://user-images.githubusercontent.com/35535130/181385169-87f968a9-4545-4a49-a8d2-ae4f9c5d6a97.png)

2022-07-27 22:47 UTC, keroloussamy commented on index.html
> +    </ul>
- [ ] Kindly add the rest of links to match the original layout.

![image](https://user-images.githubusercontent.com/35535130/181385399-fe3ff339-baea-49dc-a70a-be7640fd014d.png)

![image](https://user-images.githubusercontent.com/35535130/181385425-f33b691d-6d35-4e3b-a5cc-7f1100dbdf70.png)

2022-07-28 21:14 UTC, MeqdamAlqudah approved these changes
Hi @carlosmuerto , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media1.giphy.com/media/mCIjCgs3nWQWfJZvPA/200w.webp?cid=ecf05e47o0f3hv1ug0vf0doz9beba5fyq42t3bk3t546j29n&rid=200w.webp&ct=g)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 21:14 UTC, merged